# Maven

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(2725c70b-fd88-47b9-8dbf-0cdceb5a0cb5)'
    appType: 'webAppLinux'
    WebAppName: 'rest-service-1746871517626'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    DeploymentTypeLinux: 'oneDeploy'
